package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "ingresosdb")
public class Address implements java.io.Serializable {

	private Integer id;
	private Localities localities;
	private String address;
	private Date cat;
	private int cbu;
	private String colony;
	private boolean fdl;
	private String interiorNumber;
	private Double latitude;
	private Double longitude;
	private int luu;
	private String outdoorNumber;
	private Date uat;
	private String zipcode;

	public Address() {
	}

	public Address(Localities localities, String address, Date cat, int cbu, boolean fdl, int luu, String outdoorNumber,
			Date uat, String zipcode) {
		this.localities = localities;
		this.address = address;
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.luu = luu;
		this.outdoorNumber = outdoorNumber;
		this.uat = uat;
		this.zipcode = zipcode;
	}

	public Address(Localities localities, String address, Date cat, int cbu, String colony, boolean fdl,
			String interiorNumber, Double latitude, Double longitude, int luu, String outdoorNumber, Date uat,
			String zipcode) {
		this.localities = localities;
		this.address = address;
		this.cat = cat;
		this.cbu = cbu;
		this.colony = colony;
		this.fdl = fdl;
		this.interiorNumber = interiorNumber;
		this.latitude = latitude;
		this.longitude = longitude;
		this.luu = luu;
		this.outdoorNumber = outdoorNumber;
		this.uat = uat;
		this.zipcode = zipcode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_locality", nullable = false)
	public Localities getLocalities() {
		return this.localities;
	}

	public void setLocalities(Localities localities) {
		this.localities = localities;
	}

	@Column(name = "address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "colony", length = 200)
	public String getColony() {
		return this.colony;
	}

	public void setColony(String colony) {
		this.colony = colony;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "interior_number", length = 20)
	public String getInteriorNumber() {
		return this.interiorNumber;
	}

	public void setInteriorNumber(String interiorNumber) {
		this.interiorNumber = interiorNumber;
	}

	@Column(name = "latitude", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 22, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "outdoor_number", nullable = false, length = 20)
	public String getOutdoorNumber() {
		return this.outdoorNumber;
	}

	public void setOutdoorNumber(String outdoorNumber) {
		this.outdoorNumber = outdoorNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@Column(name = "zipcode", nullable = false, length = 8)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

}
