package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Banks generated by hbm2java
 */
@Entity
@Table(name = "banks", catalog = "ingresosdb")
public class Banks implements java.io.Serializable {

	private Integer id;
	private String account;
	private String accountingAccount;
	private String agreement;
	private String branchOffice;
	private Date cat;
	private int cbu;
	private Date creationDate;
	private boolean fdl;
	private int luu;
	private char movement;
	private String name;
	private char nature;
	private Date uat;

	public Banks() {
	}

	public Banks(String account, String accountingAccount, Date cat, int cbu, Date creationDate, boolean fdl, int luu,
			char movement, String name, char nature, Date uat) {
		this.account = account;
		this.accountingAccount = accountingAccount;
		this.cat = cat;
		this.cbu = cbu;
		this.creationDate = creationDate;
		this.fdl = fdl;
		this.luu = luu;
		this.movement = movement;
		this.name = name;
		this.nature = nature;
		this.uat = uat;
	}

	public Banks(String account, String accountingAccount, String agreement, String branchOffice, Date cat, int cbu,
			Date creationDate, boolean fdl, int luu, char movement, String name, char nature, Date uat) {
		this.account = account;
		this.accountingAccount = accountingAccount;
		this.agreement = agreement;
		this.branchOffice = branchOffice;
		this.cat = cat;
		this.cbu = cbu;
		this.creationDate = creationDate;
		this.fdl = fdl;
		this.luu = luu;
		this.movement = movement;
		this.name = name;
		this.nature = nature;
		this.uat = uat;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account", nullable = false, length = 20)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "accounting_account", nullable = false, length = 21)
	public String getAccountingAccount() {
		return this.accountingAccount;
	}

	public void setAccountingAccount(String accountingAccount) {
		this.accountingAccount = accountingAccount;
	}

	@Column(name = "agreement", length = 20)
	public String getAgreement() {
		return this.agreement;
	}

	public void setAgreement(String agreement) {
		this.agreement = agreement;
	}

	@Column(name = "branch_office", length = 40)
	public String getBranchOffice() {
		return this.branchOffice;
	}

	public void setBranchOffice(String branchOffice) {
		this.branchOffice = branchOffice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "movement", nullable = false, length = 1)
	public char getMovement() {
		return this.movement;
	}

	public void setMovement(char movement) {
		this.movement = movement;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "nature", nullable = false, length = 1)
	public char getNature() {
		return this.nature;
	}

	public void setNature(char nature) {
		this.nature = nature;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

}
