package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BdSepomexId generated by hbm2java
 */
@Embeddable
public class BdSepomexId implements java.io.Serializable {

	private String CCveCiudad;
	private String CEstado;
	private String CMunicipio;
	private String DAsenta;
	private String DCiudad;
	private String DCodigo;
	private String DEstado;
	private String DMunicipio;
	private String DTipoAsenta;
	private String DZona;

	public BdSepomexId() {
	}

	public BdSepomexId(String CCveCiudad, String CEstado, String CMunicipio, String DAsenta, String DCiudad,
			String DCodigo, String DEstado, String DMunicipio, String DTipoAsenta, String DZona) {
		this.CCveCiudad = CCveCiudad;
		this.CEstado = CEstado;
		this.CMunicipio = CMunicipio;
		this.DAsenta = DAsenta;
		this.DCiudad = DCiudad;
		this.DCodigo = DCodigo;
		this.DEstado = DEstado;
		this.DMunicipio = DMunicipio;
		this.DTipoAsenta = DTipoAsenta;
		this.DZona = DZona;
	}

	@Column(name = "c_cve_ciudad", nullable = false, length = 10)
	public String getCCveCiudad() {
		return this.CCveCiudad;
	}

	public void setCCveCiudad(String CCveCiudad) {
		this.CCveCiudad = CCveCiudad;
	}

	@Column(name = "c_estado", nullable = false, length = 40)
	public String getCEstado() {
		return this.CEstado;
	}

	public void setCEstado(String CEstado) {
		this.CEstado = CEstado;
	}

	@Column(name = "c_municipio", nullable = false, length = 10)
	public String getCMunicipio() {
		return this.CMunicipio;
	}

	public void setCMunicipio(String CMunicipio) {
		this.CMunicipio = CMunicipio;
	}

	@Column(name = "d_asenta", nullable = false, length = 200)
	public String getDAsenta() {
		return this.DAsenta;
	}

	public void setDAsenta(String DAsenta) {
		this.DAsenta = DAsenta;
	}

	@Column(name = "d_ciudad", nullable = false, length = 200)
	public String getDCiudad() {
		return this.DCiudad;
	}

	public void setDCiudad(String DCiudad) {
		this.DCiudad = DCiudad;
	}

	@Column(name = "d_codigo", nullable = false, length = 10)
	public String getDCodigo() {
		return this.DCodigo;
	}

	public void setDCodigo(String DCodigo) {
		this.DCodigo = DCodigo;
	}

	@Column(name = "d_estado", nullable = false, length = 200)
	public String getDEstado() {
		return this.DEstado;
	}

	public void setDEstado(String DEstado) {
		this.DEstado = DEstado;
	}

	@Column(name = "d_municipio", nullable = false, length = 200)
	public String getDMunicipio() {
		return this.DMunicipio;
	}

	public void setDMunicipio(String DMunicipio) {
		this.DMunicipio = DMunicipio;
	}

	@Column(name = "d_tipo_asenta", nullable = false, length = 100)
	public String getDTipoAsenta() {
		return this.DTipoAsenta;
	}

	public void setDTipoAsenta(String DTipoAsenta) {
		this.DTipoAsenta = DTipoAsenta;
	}

	@Column(name = "d_zona", nullable = false, length = 20)
	public String getDZona() {
		return this.DZona;
	}

	public void setDZona(String DZona) {
		this.DZona = DZona;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BdSepomexId))
			return false;
		BdSepomexId castOther = (BdSepomexId) other;

		return ((this.getCCveCiudad() == castOther.getCCveCiudad()) || (this.getCCveCiudad() != null
				&& castOther.getCCveCiudad() != null && this.getCCveCiudad().equals(castOther.getCCveCiudad())))
				&& ((this.getCEstado() == castOther.getCEstado()) || (this.getCEstado() != null
						&& castOther.getCEstado() != null && this.getCEstado().equals(castOther.getCEstado())))
				&& ((this.getCMunicipio() == castOther.getCMunicipio()) || (this.getCMunicipio() != null
						&& castOther.getCMunicipio() != null && this.getCMunicipio().equals(castOther.getCMunicipio())))
				&& ((this.getDAsenta() == castOther.getDAsenta()) || (this.getDAsenta() != null
						&& castOther.getDAsenta() != null && this.getDAsenta().equals(castOther.getDAsenta())))
				&& ((this.getDCiudad() == castOther.getDCiudad()) || (this.getDCiudad() != null
						&& castOther.getDCiudad() != null && this.getDCiudad().equals(castOther.getDCiudad())))
				&& ((this.getDCodigo() == castOther.getDCodigo()) || (this.getDCodigo() != null
						&& castOther.getDCodigo() != null && this.getDCodigo().equals(castOther.getDCodigo())))
				&& ((this.getDEstado() == castOther.getDEstado()) || (this.getDEstado() != null
						&& castOther.getDEstado() != null && this.getDEstado().equals(castOther.getDEstado())))
				&& ((this.getDMunicipio() == castOther.getDMunicipio()) || (this.getDMunicipio() != null
						&& castOther.getDMunicipio() != null && this.getDMunicipio().equals(castOther.getDMunicipio())))
				&& ((this.getDTipoAsenta() == castOther.getDTipoAsenta())
						|| (this.getDTipoAsenta() != null && castOther.getDTipoAsenta() != null
								&& this.getDTipoAsenta().equals(castOther.getDTipoAsenta())))
				&& ((this.getDZona() == castOther.getDZona()) || (this.getDZona() != null
						&& castOther.getDZona() != null && this.getDZona().equals(castOther.getDZona())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCCveCiudad() == null ? 0 : this.getCCveCiudad().hashCode());
		result = 37 * result + (getCEstado() == null ? 0 : this.getCEstado().hashCode());
		result = 37 * result + (getCMunicipio() == null ? 0 : this.getCMunicipio().hashCode());
		result = 37 * result + (getDAsenta() == null ? 0 : this.getDAsenta().hashCode());
		result = 37 * result + (getDCiudad() == null ? 0 : this.getDCiudad().hashCode());
		result = 37 * result + (getDCodigo() == null ? 0 : this.getDCodigo().hashCode());
		result = 37 * result + (getDEstado() == null ? 0 : this.getDEstado().hashCode());
		result = 37 * result + (getDMunicipio() == null ? 0 : this.getDMunicipio().hashCode());
		result = 37 * result + (getDTipoAsenta() == null ? 0 : this.getDTipoAsenta().hashCode());
		result = 37 * result + (getDZona() == null ? 0 : this.getDZona().hashCode());
		return result;
	}

}
