package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BdSepomex generated by hbm2java
 */
@Entity
@Table(name = "bd_sepomex", catalog = "ingresosdb")
public class BdSepomex implements java.io.Serializable {

	private BdSepomexId id;

	public BdSepomex() {
	}

	public BdSepomex(BdSepomexId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "CCveCiudad", column = @Column(name = "c_cve_ciudad", nullable = false, length = 10)),
			@AttributeOverride(name = "CEstado", column = @Column(name = "c_estado", nullable = false, length = 40)),
			@AttributeOverride(name = "CMunicipio", column = @Column(name = "c_municipio", nullable = false, length = 10)),
			@AttributeOverride(name = "DAsenta", column = @Column(name = "d_asenta", nullable = false, length = 200)),
			@AttributeOverride(name = "DCiudad", column = @Column(name = "d_ciudad", nullable = false, length = 200)),
			@AttributeOverride(name = "DCodigo", column = @Column(name = "d_codigo", nullable = false, length = 10)),
			@AttributeOverride(name = "DEstado", column = @Column(name = "d_estado", nullable = false, length = 200)),
			@AttributeOverride(name = "DMunicipio", column = @Column(name = "d_municipio", nullable = false, length = 200)),
			@AttributeOverride(name = "DTipoAsenta", column = @Column(name = "d_tipo_asenta", nullable = false, length = 100)),
			@AttributeOverride(name = "DZona", column = @Column(name = "d_zona", nullable = false, length = 20)) })
	public BdSepomexId getId() {
		return this.id;
	}

	public void setId(BdSepomexId id) {
		this.id = id;
	}

}
