package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatalogsFundingSources generated by hbm2java
 */
@Entity
@Table(name = "catalogs_funding_sources", catalog = "ingresosdb")
public class CatalogsFundingSources implements java.io.Serializable {

	private Integer id;
	private Date cat;
	private int cbu;
	private String description;
	private boolean fdl;
	private String idBase36;
	private int luu;
	private Date uat;
	private Set<CatalogsSubfundingSources> catalogsSubfundingSourceses = new HashSet<CatalogsSubfundingSources>(0);

	public CatalogsFundingSources() {
	}

	public CatalogsFundingSources(Date cat, int cbu, String description, boolean fdl, String idBase36, int luu,
			Date uat) {
		this.cat = cat;
		this.cbu = cbu;
		this.description = description;
		this.fdl = fdl;
		this.idBase36 = idBase36;
		this.luu = luu;
		this.uat = uat;
	}

	public CatalogsFundingSources(Date cat, int cbu, String description, boolean fdl, String idBase36, int luu,
			Date uat, Set<CatalogsSubfundingSources> catalogsSubfundingSourceses) {
		this.cat = cat;
		this.cbu = cbu;
		this.description = description;
		this.fdl = fdl;
		this.idBase36 = idBase36;
		this.luu = luu;
		this.uat = uat;
		this.catalogsSubfundingSourceses = catalogsSubfundingSourceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "id_base36", nullable = false, length = 2)
	public String getIdBase36() {
		return this.idBase36;
	}

	public void setIdBase36(String idBase36) {
		this.idBase36 = idBase36;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogsFundingSources")
	public Set<CatalogsSubfundingSources> getCatalogsSubfundingSourceses() {
		return this.catalogsSubfundingSourceses;
	}

	public void setCatalogsSubfundingSourceses(Set<CatalogsSubfundingSources> catalogsSubfundingSourceses) {
		this.catalogsSubfundingSourceses = catalogsSubfundingSourceses;
	}

}
