package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatalogMatrixEntryIncome generated by hbm2java
 */
@Entity
@Table(name = "catalog_matrix_entry_income", catalog = "ingresosdb")
public class CatalogMatrixEntryIncome implements java.io.Serializable {

	private String cri;
	private String accountCharge;
	private String accountPayment;
	private Date cat;
	private int cbu;
	private String charge;
	private boolean fdl;
	private int luu;
	private String nameCri;
	private String payment;
	private Date uat;

	public CatalogMatrixEntryIncome() {
	}

	public CatalogMatrixEntryIncome(String cri, Date cat, int cbu, boolean fdl, int luu, String nameCri, Date uat) {
		this.cri = cri;
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.luu = luu;
		this.nameCri = nameCri;
		this.uat = uat;
	}

	public CatalogMatrixEntryIncome(String cri, String accountCharge, String accountPayment, Date cat, int cbu,
			String charge, boolean fdl, int luu, String nameCri, String payment, Date uat) {
		this.cri = cri;
		this.accountCharge = accountCharge;
		this.accountPayment = accountPayment;
		this.cat = cat;
		this.cbu = cbu;
		this.charge = charge;
		this.fdl = fdl;
		this.luu = luu;
		this.nameCri = nameCri;
		this.payment = payment;
		this.uat = uat;
	}

	@Id

	@Column(name = "cri", unique = true, nullable = false, length = 4)
	public String getCri() {
		return this.cri;
	}

	public void setCri(String cri) {
		this.cri = cri;
	}

	@Column(name = "account_charge", length = 150)
	public String getAccountCharge() {
		return this.accountCharge;
	}

	public void setAccountCharge(String accountCharge) {
		this.accountCharge = accountCharge;
	}

	@Column(name = "account_payment", length = 150)
	public String getAccountPayment() {
		return this.accountPayment;
	}

	public void setAccountPayment(String accountPayment) {
		this.accountPayment = accountPayment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "charge", length = 5)
	public String getCharge() {
		return this.charge;
	}

	public void setCharge(String charge) {
		this.charge = charge;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "name_cri", nullable = false, length = 200)
	public String getNameCri() {
		return this.nameCri;
	}

	public void setNameCri(String nameCri) {
		this.nameCri = nameCri;
	}

	@Column(name = "payment", length = 5)
	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

}
