package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EntityOffices generated by hbm2java
 */
@Entity
@Table(name = "entity_offices", catalog = "ingresosdb")
public class EntityOffices implements java.io.Serializable {

	private Integer id;
	private Date cat;
	private int cbu;
	private boolean fdl;
	private String idBase36;
	private String idExternal;
	private int luu;
	private String name;
	private Date uat;
	private int idTypeOffice;

	public EntityOffices() {
	}

	public EntityOffices(Date cat, int cbu, boolean fdl, int luu, String name, Date uat, int idTypeOffice) {
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.luu = luu;
		this.name = name;
		this.uat = uat;
		this.idTypeOffice = idTypeOffice;
	}

	public EntityOffices(Date cat, int cbu, boolean fdl, String idBase36, String idExternal, int luu, String name,
			Date uat, int idTypeOffice) {
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.idBase36 = idBase36;
		this.idExternal = idExternal;
		this.luu = luu;
		this.name = name;
		this.uat = uat;
		this.idTypeOffice = idTypeOffice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "id_base36", length = 2)
	public String getIdBase36() {
		return this.idBase36;
	}

	public void setIdBase36(String idBase36) {
		this.idBase36 = idBase36;
	}

	@Column(name = "id_external", length = 10)
	public String getIdExternal() {
		return this.idExternal;
	}

	public void setIdExternal(String idExternal) {
		this.idExternal = idExternal;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@Column(name = "id_type_office", nullable = false)
	public int getIdTypeOffice() {
		return this.idTypeOffice;
	}

	public void setIdTypeOffice(int idTypeOffice) {
		this.idTypeOffice = idTypeOffice;
	}

}
