package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InformativeConcept generated by hbm2java
 */
@Entity
@Table(name = "informative_concept", catalog = "ingresosdb")
public class InformativeConcept implements java.io.Serializable {

	private Integer id;
	private Date cat;
	private int cbu;
	private boolean fdl;
	private String idExternal;
	private boolean isData;
	private int luu;
	private String name;
	private Short orderN;
	private String typeData;
	private Date uat;
	private int idObligation;

	public InformativeConcept() {
	}

	public InformativeConcept(Date cat, int cbu, boolean fdl, String idExternal, boolean isData, int luu, String name,
			String typeData, Date uat, int idObligation) {
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.idExternal = idExternal;
		this.isData = isData;
		this.luu = luu;
		this.name = name;
		this.typeData = typeData;
		this.uat = uat;
		this.idObligation = idObligation;
	}

	public InformativeConcept(Date cat, int cbu, boolean fdl, String idExternal, boolean isData, int luu, String name,
			Short orderN, String typeData, Date uat, int idObligation) {
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.idExternal = idExternal;
		this.isData = isData;
		this.luu = luu;
		this.name = name;
		this.orderN = orderN;
		this.typeData = typeData;
		this.uat = uat;
		this.idObligation = idObligation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "id_external", nullable = false, length = 10)
	public String getIdExternal() {
		return this.idExternal;
	}

	public void setIdExternal(String idExternal) {
		this.idExternal = idExternal;
	}

	@Column(name = "is_data", nullable = false)
	public boolean isIsData() {
		return this.isData;
	}

	public void setIsData(boolean isData) {
		this.isData = isData;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "order_n")
	public Short getOrderN() {
		return this.orderN;
	}

	public void setOrderN(Short orderN) {
		this.orderN = orderN;
	}

	@Column(name = "type_data", nullable = false, length = 50)
	public String getTypeData() {
		return this.typeData;
	}

	public void setTypeData(String typeData) {
		this.typeData = typeData;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@Column(name = "id_obligation", nullable = false)
	public int getIdObligation() {
		return this.idObligation;
	}

	public void setIdObligation(int idObligation) {
		this.idObligation = idObligation;
	}

}
