package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Localities generated by hbm2java
 */
@Entity
@Table(name = "localities", catalog = "ingresosdb")
public class Localities implements java.io.Serializable {

	private Integer id;
	private Date cat;
	private int cbu;
	private boolean fdl;
	private String idExternal;
	private Double latitude;
	private Double longitude;
	private int luu;
	private String name;
	private Date uat;
	private String zipcode;
	private int idMunicipality;
	private Set<Address> addresses = new HashSet<Address>(0);

	public Localities() {
	}

	public Localities(Date cat, int cbu, boolean fdl, String idExternal, int luu, String name, Date uat, String zipcode,
			int idMunicipality) {
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.idExternal = idExternal;
		this.luu = luu;
		this.name = name;
		this.uat = uat;
		this.zipcode = zipcode;
		this.idMunicipality = idMunicipality;
	}

	public Localities(Date cat, int cbu, boolean fdl, String idExternal, Double latitude, Double longitude, int luu,
			String name, Date uat, String zipcode, int idMunicipality, Set<Address> addresses) {
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.idExternal = idExternal;
		this.latitude = latitude;
		this.longitude = longitude;
		this.luu = luu;
		this.name = name;
		this.uat = uat;
		this.zipcode = zipcode;
		this.idMunicipality = idMunicipality;
		this.addresses = addresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "id_external", nullable = false, length = 10)
	public String getIdExternal() {
		return this.idExternal;
	}

	public void setIdExternal(String idExternal) {
		this.idExternal = idExternal;
	}

	@Column(name = "latitude", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 22, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@Column(name = "zipcode", nullable = false, length = 8)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "id_municipality", nullable = false)
	public int getIdMunicipality() {
		return this.idMunicipality;
	}

	public void setIdMunicipality(int idMunicipality) {
		this.idMunicipality = idMunicipality;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localities")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
