package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReferenceGlobal generated by hbm2java
 */
@Entity
@Table(name = "reference_global", catalog = "ingresosdb")
public class ReferenceGlobal implements java.io.Serializable {

	private Integer id;
	private Date bankDate;
	private Date cat;
	private int cbu;
	private Date cutoffDate;
	private Date dueDate;
	private boolean fdl;
	private int luu;
	private String reference;
	private short status;
	private double totalAmount;
	private Date uat;
	private Integer idBank;
	private int idUser;

	public ReferenceGlobal() {
	}

	public ReferenceGlobal(Date bankDate, Date cat, int cbu, Date cutoffDate, Date dueDate, boolean fdl, int luu,
			String reference, short status, double totalAmount, Date uat, int idUser) {
		this.bankDate = bankDate;
		this.cat = cat;
		this.cbu = cbu;
		this.cutoffDate = cutoffDate;
		this.dueDate = dueDate;
		this.fdl = fdl;
		this.luu = luu;
		this.reference = reference;
		this.status = status;
		this.totalAmount = totalAmount;
		this.uat = uat;
		this.idUser = idUser;
	}

	public ReferenceGlobal(Date bankDate, Date cat, int cbu, Date cutoffDate, Date dueDate, boolean fdl, int luu,
			String reference, short status, double totalAmount, Date uat, Integer idBank, int idUser) {
		this.bankDate = bankDate;
		this.cat = cat;
		this.cbu = cbu;
		this.cutoffDate = cutoffDate;
		this.dueDate = dueDate;
		this.fdl = fdl;
		this.luu = luu;
		this.reference = reference;
		this.status = status;
		this.totalAmount = totalAmount;
		this.uat = uat;
		this.idBank = idBank;
		this.idUser = idUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bank_date", nullable = false, length = 19)
	public Date getBankDate() {
		return this.bankDate;
	}

	public void setBankDate(Date bankDate) {
		this.bankDate = bankDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cutoff_date", nullable = false, length = 19)
	public Date getCutoffDate() {
		return this.cutoffDate;
	}

	public void setCutoffDate(Date cutoffDate) {
		this.cutoffDate = cutoffDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "due_date", nullable = false, length = 19)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "reference", nullable = false, length = 50)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "status", nullable = false)
	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@Column(name = "total_amount", nullable = false, precision = 22, scale = 0)
	public double getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(double totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@Column(name = "id_bank")
	public Integer getIdBank() {
		return this.idBank;
	}

	public void setIdBank(Integer idBank) {
		this.idBank = idBank;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

}
