package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaxpayerRegistry generated by hbm2java
 */
@Entity
@Table(name = "taxpayer_registry", catalog = "ingresosdb")
public class TaxpayerRegistry implements java.io.Serializable {

	private Integer id;
	private Date cat;
	private int cbu;
	private String cellphone;
	private String curp;
	private String email;
	private boolean fdl;
	private String firstName;
	private short genere;
	private String ine;
	private String lastName;
	private int luu;
	private String name;
	private String rfc;
	private String telephone;
	private short typePerson;
	private Date uat;
	private int idAddress;

	public TaxpayerRegistry() {
	}

	public TaxpayerRegistry(Date cat, int cbu, boolean fdl, short genere, int luu, String name, String rfc,
			short typePerson, Date uat, int idAddress) {
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.genere = genere;
		this.luu = luu;
		this.name = name;
		this.rfc = rfc;
		this.typePerson = typePerson;
		this.uat = uat;
		this.idAddress = idAddress;
	}

	public TaxpayerRegistry(Date cat, int cbu, String cellphone, String curp, String email, boolean fdl,
			String firstName, short genere, String ine, String lastName, int luu, String name, String rfc,
			String telephone, short typePerson, Date uat, int idAddress) {
		this.cat = cat;
		this.cbu = cbu;
		this.cellphone = cellphone;
		this.curp = curp;
		this.email = email;
		this.fdl = fdl;
		this.firstName = firstName;
		this.genere = genere;
		this.ine = ine;
		this.lastName = lastName;
		this.luu = luu;
		this.name = name;
		this.rfc = rfc;
		this.telephone = telephone;
		this.typePerson = typePerson;
		this.uat = uat;
		this.idAddress = idAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "cellphone", length = 20)
	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	@Column(name = "curp", length = 20)
	public String getCurp() {
		return this.curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "first_name", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "genere", nullable = false)
	public short getGenere() {
		return this.genere;
	}

	public void setGenere(short genere) {
		this.genere = genere;
	}

	@Column(name = "ine", length = 20)
	public String getIne() {
		return this.ine;
	}

	public void setIne(String ine) {
		this.ine = ine;
	}

	@Column(name = "last_name", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "rfc", nullable = false, length = 15)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "telephone", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "type_person", nullable = false)
	public short getTypePerson() {
		return this.typePerson;
	}

	public void setTypePerson(short typePerson) {
		this.typePerson = typePerson;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@Column(name = "id_address", nullable = false)
	public int getIdAddress() {
		return this.idAddress;
	}

	public void setIdAddress(int idAddress) {
		this.idAddress = idAddress;
	}

}
