package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionInformative generated by hbm2java
 */
@Entity
@Table(name = "transaction_informative", catalog = "ingresosdb")
public class TransactionInformative implements java.io.Serializable {

	private Integer id;
	private Date cat;
	private int cbu;
	private boolean fdl;
	private int luu;
	private Date uat;
	private Double valueConcept;
	private String valueData;
	private int idInformativeConcept;
	private int id1TransactionH;

	public TransactionInformative() {
	}

	public TransactionInformative(Date cat, int cbu, boolean fdl, int luu, Date uat, int idInformativeConcept,
			int id1TransactionH) {
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.luu = luu;
		this.uat = uat;
		this.idInformativeConcept = idInformativeConcept;
		this.id1TransactionH = id1TransactionH;
	}

	public TransactionInformative(Date cat, int cbu, boolean fdl, int luu, Date uat, Double valueConcept,
			String valueData, int idInformativeConcept, int id1TransactionH) {
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.luu = luu;
		this.uat = uat;
		this.valueConcept = valueConcept;
		this.valueData = valueData;
		this.idInformativeConcept = idInformativeConcept;
		this.id1TransactionH = id1TransactionH;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@Column(name = "value_concept", precision = 22, scale = 0)
	public Double getValueConcept() {
		return this.valueConcept;
	}

	public void setValueConcept(Double valueConcept) {
		this.valueConcept = valueConcept;
	}

	@Column(name = "value_data", length = 200)
	public String getValueData() {
		return this.valueData;
	}

	public void setValueData(String valueData) {
		this.valueData = valueData;
	}

	@Column(name = "id_informative_concept", nullable = false)
	public int getIdInformativeConcept() {
		return this.idInformativeConcept;
	}

	public void setIdInformativeConcept(int idInformativeConcept) {
		this.idInformativeConcept = idInformativeConcept;
	}

	@Column(name = "id1_transaction_h", nullable = false)
	public int getId1TransactionH() {
		return this.id1TransactionH;
	}

	public void setId1TransactionH(int id1TransactionH) {
		this.id1TransactionH = id1TransactionH;
	}

}
