package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionH generated by hbm2java
 */
@Entity
@Table(name = "transaction_h", catalog = "ingresosdb")
public class TransactionH implements java.io.Serializable {

	private Integer id;
	private String authorization;
	private Date bankDate;
	private Date cat;
	private int cbu;
	private boolean fdl;
	private String folio;
	private String folioFiscal;
	private double globalAmount;
	private Boolean isInvoice;
	private String leged;
	private int luu;
	private String note;
	private String payPeriod;
	private Date paymentDate;
	private Date transactDate;
	private Date uat;
	private int idEntityOffice;
	private int idPaymentForm;
	private int idPaymentMethod;
	private int idStatusTransaction;
	private int idTaxpayerObligation;
	private int idUser;

	public TransactionH() {
	}

	public TransactionH(Date bankDate, Date cat, int cbu, boolean fdl, double globalAmount, int luu, String payPeriod,
			Date paymentDate, Date transactDate, Date uat, int idEntityOffice, int idPaymentForm, int idPaymentMethod,
			int idStatusTransaction, int idTaxpayerObligation, int idUser) {
		this.bankDate = bankDate;
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.globalAmount = globalAmount;
		this.luu = luu;
		this.payPeriod = payPeriod;
		this.paymentDate = paymentDate;
		this.transactDate = transactDate;
		this.uat = uat;
		this.idEntityOffice = idEntityOffice;
		this.idPaymentForm = idPaymentForm;
		this.idPaymentMethod = idPaymentMethod;
		this.idStatusTransaction = idStatusTransaction;
		this.idTaxpayerObligation = idTaxpayerObligation;
		this.idUser = idUser;
	}

	public TransactionH(String authorization, Date bankDate, Date cat, int cbu, boolean fdl, String folio,
			String folioFiscal, double globalAmount, Boolean isInvoice, String leged, int luu, String note,
			String payPeriod, Date paymentDate, Date transactDate, Date uat, int idEntityOffice, int idPaymentForm,
			int idPaymentMethod, int idStatusTransaction, int idTaxpayerObligation, int idUser) {
		this.authorization = authorization;
		this.bankDate = bankDate;
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.folio = folio;
		this.folioFiscal = folioFiscal;
		this.globalAmount = globalAmount;
		this.isInvoice = isInvoice;
		this.leged = leged;
		this.luu = luu;
		this.note = note;
		this.payPeriod = payPeriod;
		this.paymentDate = paymentDate;
		this.transactDate = transactDate;
		this.uat = uat;
		this.idEntityOffice = idEntityOffice;
		this.idPaymentForm = idPaymentForm;
		this.idPaymentMethod = idPaymentMethod;
		this.idStatusTransaction = idStatusTransaction;
		this.idTaxpayerObligation = idTaxpayerObligation;
		this.idUser = idUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "authorization", length = 50)
	public String getAuthorization() {
		return this.authorization;
	}

	public void setAuthorization(String authorization) {
		this.authorization = authorization;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bank_date", nullable = false, length = 19)
	public Date getBankDate() {
		return this.bankDate;
	}

	public void setBankDate(Date bankDate) {
		this.bankDate = bankDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "folio", length = 100)
	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	@Column(name = "folio_fiscal", length = 150)
	public String getFolioFiscal() {
		return this.folioFiscal;
	}

	public void setFolioFiscal(String folioFiscal) {
		this.folioFiscal = folioFiscal;
	}

	@Column(name = "global_amount", nullable = false, precision = 22, scale = 0)
	public double getGlobalAmount() {
		return this.globalAmount;
	}

	public void setGlobalAmount(double globalAmount) {
		this.globalAmount = globalAmount;
	}

	@Column(name = "is_invoice")
	public Boolean getIsInvoice() {
		return this.isInvoice;
	}

	public void setIsInvoice(Boolean isInvoice) {
		this.isInvoice = isInvoice;
	}

	@Column(name = "leged")
	public String getLeged() {
		return this.leged;
	}

	public void setLeged(String leged) {
		this.leged = leged;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "pay_period", nullable = false, length = 50)
	public String getPayPeriod() {
		return this.payPeriod;
	}

	public void setPayPeriod(String payPeriod) {
		this.payPeriod = payPeriod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_date", nullable = false, length = 19)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transact_date", nullable = false, length = 19)
	public Date getTransactDate() {
		return this.transactDate;
	}

	public void setTransactDate(Date transactDate) {
		this.transactDate = transactDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@Column(name = "id_entity_office", nullable = false)
	public int getIdEntityOffice() {
		return this.idEntityOffice;
	}

	public void setIdEntityOffice(int idEntityOffice) {
		this.idEntityOffice = idEntityOffice;
	}

	@Column(name = "id_payment_form", nullable = false)
	public int getIdPaymentForm() {
		return this.idPaymentForm;
	}

	public void setIdPaymentForm(int idPaymentForm) {
		this.idPaymentForm = idPaymentForm;
	}

	@Column(name = "id_payment_method", nullable = false)
	public int getIdPaymentMethod() {
		return this.idPaymentMethod;
	}

	public void setIdPaymentMethod(int idPaymentMethod) {
		this.idPaymentMethod = idPaymentMethod;
	}

	@Column(name = "id_status_transaction", nullable = false)
	public int getIdStatusTransaction() {
		return this.idStatusTransaction;
	}

	public void setIdStatusTransaction(int idStatusTransaction) {
		this.idStatusTransaction = idStatusTransaction;
	}

	@Column(name = "id_taxpayer_obligation", nullable = false)
	public int getIdTaxpayerObligation() {
		return this.idTaxpayerObligation;
	}

	public void setIdTaxpayerObligation(int idTaxpayerObligation) {
		this.idTaxpayerObligation = idTaxpayerObligation;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

}
