package com.ingresos.backend.models.entity;
// Generated 7/12/2018 11:37:07 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransactionDetail generated by hbm2java
 */
@Entity
@Table(name = "transaction_detail", catalog = "ingresosdb")
public class TransactionDetail implements java.io.Serializable {

	private Integer id;
	private double amount;
	private Date cat;
	private int cbu;
	private boolean fdl;
	private boolean isDiscount;
	private int luu;
	private double percentage;
	private short quanty;
	private double totalAmount;
	private Date uat;
	private int idConcept;
	private int idTransactionH;
	private int idUser;

	public TransactionDetail() {
	}

	public TransactionDetail(double amount, Date cat, int cbu, boolean fdl, boolean isDiscount, int luu,
			double percentage, short quanty, double totalAmount, Date uat, int idConcept, int idTransactionH,
			int idUser) {
		this.amount = amount;
		this.cat = cat;
		this.cbu = cbu;
		this.fdl = fdl;
		this.isDiscount = isDiscount;
		this.luu = luu;
		this.percentage = percentage;
		this.quanty = quanty;
		this.totalAmount = totalAmount;
		this.uat = uat;
		this.idConcept = idConcept;
		this.idTransactionH = idTransactionH;
		this.idUser = idUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "amount", nullable = false, precision = 22, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cat", nullable = false, length = 19)
	public Date getCat() {
		return this.cat;
	}

	public void setCat(Date cat) {
		this.cat = cat;
	}

	@Column(name = "cbu", nullable = false)
	public int getCbu() {
		return this.cbu;
	}

	public void setCbu(int cbu) {
		this.cbu = cbu;
	}

	@Column(name = "fdl", nullable = false)
	public boolean isFdl() {
		return this.fdl;
	}

	public void setFdl(boolean fdl) {
		this.fdl = fdl;
	}

	@Column(name = "is_discount", nullable = false)
	public boolean isIsDiscount() {
		return this.isDiscount;
	}

	public void setIsDiscount(boolean isDiscount) {
		this.isDiscount = isDiscount;
	}

	@Column(name = "luu", nullable = false)
	public int getLuu() {
		return this.luu;
	}

	public void setLuu(int luu) {
		this.luu = luu;
	}

	@Column(name = "percentage", nullable = false, precision = 22, scale = 0)
	public double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(double percentage) {
		this.percentage = percentage;
	}

	@Column(name = "quanty", nullable = false)
	public short getQuanty() {
		return this.quanty;
	}

	public void setQuanty(short quanty) {
		this.quanty = quanty;
	}

	@Column(name = "total_amount", nullable = false, precision = 22, scale = 0)
	public double getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(double totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "uat", nullable = false, length = 19)
	public Date getUat() {
		return this.uat;
	}

	public void setUat(Date uat) {
		this.uat = uat;
	}

	@Column(name = "id_concept", nullable = false)
	public int getIdConcept() {
		return this.idConcept;
	}

	public void setIdConcept(int idConcept) {
		this.idConcept = idConcept;
	}

	@Column(name = "id_transaction_h", nullable = false)
	public int getIdTransactionH() {
		return this.idTransactionH;
	}

	public void setIdTransactionH(int idTransactionH) {
		this.idTransactionH = idTransactionH;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

}
